query getCommitments {
  allCommitments{
    data {
      _id
      entrytitle
      duration
      parent {
        _id
				link{
          _id
          entrytitle
        }
      }
      selfAsParent{
        _id
      }
      duedate
      complete
      rank
    }
  }
}