type Crouleur {
  identifier: String! @unique
  name: String
  email: String @unique
}

type Commitment {
  entrytitle: String!
  duedate: String
  complete: Boolean!
  parent: Commitment
  rank: Int
  crouleur: Crouleur
}

type Prerequisite {
        commitmentId: String!
        prerequisiteId: String!
        commitment: Commitment!
        prerequisite: Commitment!
        crouleur: Crouleur!
}

type Query {
  allCrouleurs: [Crouleur!]
  allCommitments: [Commitment!]
}